### PR TITLE
fixes test; formatter test

### LINKED ISSUE #148: test coverage for `fix` service call

### PR DESCRIPTION
**Pull request by devoncarew**
@lukechurch 

- add a common server test for `fixes` (fix #148)
- add more coverage for the format call (w/ a position arg)
- fix a bug w the format impl

### CODE REVIEW

File: lib/src/analysis_server.dart [hunk 1]
```diff
@@ -77,7 +77,7 @@ class AnalysisServerWrapper {
 
   Future<api.FormatResponse> format(String src, int offset) async {
     var results = _formatImpl(src, offset);
-    return results.then((editResult) {
+    return results.then((EditFormatResult editResult) {
```
Comment (lukechurch) [inline lib/src/analysis_server.dart]: I prefer leaving this as en explicit type, there are too many levels of indirection to be able know what this thing is going to give my reading the code (how many different forms of result element we have in this code (!)). Otherwise it gets really unclear what this thing is yielding without a lot of hovering over.

**Comment by lukechurch** [comment]
Thanks @devoncarew.

File: lib/src/analysis_server.dart (hunk 1 above)
Comment (devoncarew) [inline lib/src/analysis_server.dart]: I added the `EditFormatResult` type annotation; I think you're saying that it aids readability, and we should keep it? If so, thats my thinking as well :)

Comment (lukechurch) [inline lib/src/analysis_server.dart]: Haha. Yes, I think I'm in strong agreement with you, and misreading the diff.

**Comment by lukechurch** [comment]
LGTM, pls merge as soon as build has completed.
